pub_rate: 1.0
analyzers:
  GPS:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'GPS'
    timeout: 5.0
    contains: ['gps_updater']
  Battery:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Battery'
    timeout: 5.0
    contains: ['batt_updater']

